[project]
name = "goodreads-user-scraper"
version = "0.1.0"
description = "Scrape a users profile page from goodreads into a csv file for import"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "pydantic>=2.11.9",
    "pydantic-extra-types>=2.10.5",
    "pytest>=8.4.2",
    "requests>=2.32.0",
]
